service: throttle-backend-apis
frameworkVersion: '>=1.28.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}

functions:
  FileUpload:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/upload_error
          method: POST
  UserAction:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/user_action
          method: POST
  DeleteUserAction:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/delete_user_action
          method: POST
  GetRawErrorData:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /editing/error
          method: POST
  GetRawImageData:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /editing/images
          method: POST
  GenerateDocument:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /generateDocument
          method: POST
  Login:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /auth/login
          method: POST
  Register:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /auth/register
          method: POST

package:
  patterns:
    - '!*/**'
    - bin/**

plugins:
  - serverless-offline
 
custom:
  serverless-offline:
    noPrependStageInUrl: true


