service: throttle-backend-apis
frameworkVersion: '>=1.28.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}

functions:
  UploadError:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/upload_error
          method: POST

  GetLatestUnresolvedJourneys:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/get_latest_unsolved
          method: POST

  UpdateErrorState:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/update_error_state
          method: POST

  UpdateFinalState:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/update_final_state
          method: POST

  InsertUserActions:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/user_action
          method: POST

  DeleteUserAction:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/delete_user_action
          method: POST

  ValidateUserAction:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/validate_user_action
          method: POST

  GetRawErrorDocs:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /editing/error
          method: POST

  GetImagesFromS3:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /editing/images
          method: POST

  GetLatestRawError:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /preDocEdit/getLatestErrorRaw
          method: POST

  GenerateDocument:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /generateDocument
          method: POST

  GetDashboard:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /dashboard/getDashboard
          method: POST

  GetDashboardDoc:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /dashboard/getDashboardDoc
          method: POST

  PublishDoc:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /dashboard/publishDoc
          method: POST

  SaveDoc:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /dashboard/saveDoc
          method: POST

  DeleteDoc:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /dashboard/deleteDoc
          method: POST

  HealthCheck:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /ping
          method: GET

package:
  patterns:
    - '!*/**'
    - bin/**

plugins:
  - serverless-offline

custom:
  serverless-offline:
    noPrependStageInUrl: true
