service: throttle-backend-apis
frameworkVersion: '>=1.28.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  # stage: ${opt:stage}

functions:
  api:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/ping
          method: GET
          
package:
  patterns:
  - '!*/**'
  - bin/main

plugins:
  - serverless-offline
 
custom:
  serverless-offline:
    noPrependStageInUrl: true

