service: throttle-backend-apis
frameworkVersion: '>=1.28.0'

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}

functions:
  FileUpload:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/upload_error
          method: POST
  UserAction:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /file_upload/user_action
          method: POST
  GetRawErrorData:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /editing/error
          method: POST
  GetRawImageData:
    handler: bin/fileUploadService/main
    events:
      - http:
          path: /editing/images
          method: POST

package:
  patterns:
    - '!*/**'
    - bin/**

plugins:
  - serverless-offline
 
custom:
  serverless-offline:
    noPrependStageInUrl: true


